source "https://rubygems.org"

gem "rbs", "~> 3.9.0"
gem "steep", "~> 1.10"
gem "prism", "~> 1.3.0"
gem "ruby-lsp", require: false, group: :development
gem "debug", require: false, group: :development, platforms: :mri
gem "test-unit"
