# Remove here if duplicated

class Module
  def ruby2_keywords: (*untyped) -> void
end

class Proc
  def ruby2_keywords: () -> self
end

module Prism
  class StringQuery
    # < 1.9.0
    def self.constant?: (String) -> bool
  end
end
