# Remove here if duplicated

class Module
  def ruby2_keywords: (*untyped) -> void
end

class Proc
  def ruby2_keywords: () -> self
end

class RubyVM
  class InstructionSequence
    def self.of: (Method | UnboundMethod | Proc) -> RubyVM::InstructionSequence?
  end
end
