%a{annotate:rdoc:skip}
module URI
  # <!-- rdoc-file=lib/uri/ftp.rb -->
  # FTP URI syntax is defined by RFC1738 section 3.2.
  #
  # This class will be redesigned because of difference of implementations; the
  # structure of its path. draft-hoffman-ftp-uri-04 is a draft but it is a good
  # summary about the de facto spec.
  # https://datatracker.ietf.org/doc/html/draft-hoffman-ftp-uri-04
  #
  class FTP < Generic
    # A Default port of 21 for URI::FTP.
    #
    DEFAULT_PORT: Integer

    # An Array of the available components for URI::FTP.
    #
    COMPONENT: Array[Symbol]

    # Typecode is "a", "i", or "d".
    #
    # * "a" indicates a text file (the FTP command was ASCII)
    # * "i" indicates a binary file (FTP command IMAGE)
    # * "d" indicates the contents of a directory should be displayed
    #
    TYPECODE: Array[String]

    # Typecode prefix ";type=".
    #
    TYPECODE_PREFIX: String

    def self.build: (Array[String | Integer | nil] args) -> instance
                  | ({ ?userinfo: String?, ?host: String?, ?port: Integer?, ?path: String?, ?typecode: String? }) -> instance

    def self.new2: (String? user, String? password, String? host, (String | Integer)? port, String path, ?String? typecode, ?boolish arg_check) -> instance

    def path: () -> String

    def set_typecode: (String? v) -> void

    def typecode: () -> String?

    def typecode=: (String typecode) -> String
  end
end
