class URI::RFC3986_Parser
  FRAGMENT: String

  HOST: Regexp

  RFC3986_URI: Regexp

  RFC3986_relative_ref: Regexp

  SCHEME: String

  SEG: String

  SEG_NC: String

  USERINFO: Regexp

  attr_reader regexp: Hash[Symbol, Regexp]

  def initialize: () -> void

  def escape: (String str, ?Regexp unsafe) -> String

  def extract: (String str, ?Array[String] schemes) -> Array[String]
             | (String str, ?Array[String] schemes) { (String) -> untyped } -> nil

  def join: (*String uris) -> URI::Generic

  def make_regexp: (?Array[String] schemes) -> Regexp

  def parse: (String uri) -> URI::Generic

  def split: (String uri) -> [ String?, String?, String?, String?, String?, String?, String?, String?, String? ]

  def unescape: (String str, ?Regexp escaped) -> String
end
