module Logger::Period
  def self.next_rotate_time: (untyped now, untyped shift_age) -> untyped

  def self.previous_period_end: (untyped now, untyped shift_age) -> untyped

  private

  def next_rotate_time: (untyped now, untyped shift_age) -> untyped

  def previous_period_end: (untyped now, untyped shift_age) -> untyped
end

Logger::Period::SiD: Integer
