use std::env;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    println!("cargo:warning=Build script is running!");

    if let Err(err) = generate() {
        panic!("build.rs failed: {err}");
    }
}

fn generate() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("bindings.rs");

    let mut file = File::create(&dest_path)?;

    writeln!(file, "// Generated by build.rs")?;
    writeln!(file, "// Do not edit this file directly")?;
    writeln!(file, "")?;

    Ok(())
}
