use serde::Deserialize;
use std::{env, error::Error, fs::File, io::Write, path::Path};

#[derive(Debug, Deserialize)]
struct Config {
    nodes: Vec<Node>,
}

#[derive(Debug, Deserialize)]
struct NodeField {
    name: String,
    c_type: String,
    c_name: Option<String>,
}

impl NodeField {
    fn c_name(&self) -> &str {
        let name = self.c_name.as_ref().unwrap_or(&self.name);
        if name == "type" { "type_" } else { name }
    }
}

#[derive(Debug, Deserialize)]
struct Node {
    name: String,
    rust_name: String,
    fields: Option<Vec<NodeField>>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let config_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../config.yml")
        .canonicalize()?;

    println!("cargo:rerun-if-changed={}", config_path.display());

    let config_file = File::open(&config_path)?;
    let mut config: Config = serde_yaml::from_reader(config_file)?;

    // Keyword and Symbol represent identifiers (interned strings), not traditional AST nodes.
    // However, the C parser defines them in `rbs_node_type` (RBS_KEYWORD, RBS_AST_SYMBOL) and
    // treats them as nodes (rbs_node_t*) in many contexts (lists, hashes).
    // We inject them into the config so they are generated as structs matching the Node pattern,
    // allowing them to be wrapped in the Node enum and handled uniformly in Rust.
    config.nodes.push(Node {
        name: "RBS::Keyword".to_string(),
        rust_name: "KeywordNode".to_string(),
        fields: None,
    });
    config.nodes.push(Node {
        name: "RBS::AST::Symbol".to_string(),
        rust_name: "SymbolNode".to_string(),
        fields: None,
    });

    config.nodes.sort_by(|a, b| a.name.cmp(&b.name));
    generate(&config)?;

    Ok(())
}

enum CIdentifier {
    Type,     // foo_bar_t
    Constant, // FOO_BAR
}

fn convert_name(name: &str, identifier: CIdentifier) -> String {
    let type_name = name.replace("::", "_");
    let lowercase = matches!(identifier, CIdentifier::Type);
    let mut out = String::new();
    let mut prev_is_lower = false;

    for ch in type_name.chars() {
        if ch.is_ascii_uppercase() {
            if prev_is_lower {
                out.push('_');
            }
            out.push(if lowercase {
                ch.to_ascii_lowercase()
            } else {
                ch
            });
            prev_is_lower = false;
        } else if ch == '_' {
            out.push(ch);
            prev_is_lower = false;
        } else {
            out.push(if lowercase {
                ch
            } else {
                ch.to_ascii_uppercase()
            });
            prev_is_lower = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        }
    }

    if lowercase {
        out.push_str("_t");
    }
    out
}

fn generate(config: &Config) -> Result<(), Box<dyn Error>> {
    let out_dir = env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("bindings.rs");

    let mut file = File::create(&dest_path)?;

    writeln!(file, "// Generated by build.rs from config.yml")?;
    writeln!(file, "// Nodes to generate: {}", config.nodes.len())?;
    writeln!(file)?;

    // TODO: Go through all of the nodes and generate the structs to back them up
    for node in &config.nodes {
        writeln!(file, "#[allow(dead_code)]")?; // TODO: Remove this once all nodes that need parser are implemented
        writeln!(file, "#[derive(Debug)]")?;
        writeln!(file, "pub struct {} {{", node.rust_name)?;
        writeln!(file, "    parser: *mut rbs_parser_t,")?;
        writeln!(
            file,
            "    pointer: *mut {},",
            convert_name(&node.name, CIdentifier::Type)
        )?;
        writeln!(file, "}}\n")?;

        writeln!(file, "impl {} {{", node.rust_name)?;
        if let Some(fields) = &node.fields {
            for field in fields {
                match field.c_type.as_str() {
                    "rbs_string" => {
                        writeln!(file, "    pub fn {}(&self) -> RBSString {{", field.name)?;
                        writeln!(
                            file,
                            "        RBSString::new(unsafe {{ &(*self.pointer).{} }})",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "bool" => {
                        writeln!(file, "    pub fn {}(&self) -> bool {{", field.name)?;
                        writeln!(file, "        unsafe {{ (*self.pointer).{} }}", field.name)?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_ast_comment" => {
                        writeln!(file, "    pub fn {}(&self) -> CommentNode {{", field.name)?;
                        writeln!(
                            file,
                            "        CommentNode {{ parser: self.parser, pointer: unsafe {{ (*self.pointer).{} }} }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_ast_declarations_class_super" => {
                        writeln!(
                            file,
                            "    pub fn {}(&self) -> ClassSuperNode {{",
                            field.name
                        )?;
                        writeln!(
                            file,
                            "        ClassSuperNode {{ parser: self.parser, pointer: unsafe {{ (*self.pointer).{} }} }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_ast_symbol" => {
                        writeln!(file, "    pub fn {}(&self) -> SymbolNode {{", field.name)?;
                        writeln!(
                            file,
                            "        SymbolNode {{ parser: self.parser, pointer: unsafe {{ (*self.pointer).{} }} }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_hash" => {
                        writeln!(file, "    pub fn {}(&self) -> RBSHash {{", field.name)?;
                        writeln!(
                            file,
                            "        RBSHash::new(self.parser, unsafe {{ (*self.pointer).{} }})",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_location" => {
                        writeln!(file, "    pub fn {}(&self) -> RBSLocation {{", field.name)?;
                        writeln!(
                            file,
                            "        RBSLocation::new(unsafe {{ (*self.pointer).{} }}, self.parser)",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_location_list" => {
                        writeln!(
                            file,
                            "    pub fn {}(&self) -> RBSLocationList {{",
                            field.name
                        )?;
                        writeln!(
                            file,
                            "        RBSLocationList::new(unsafe {{ (*self.pointer).{} }}, self.parser)",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_namespace" => {
                        writeln!(file, "    pub fn {}(&self) -> NamespaceNode {{", field.name)?;
                        writeln!(
                            file,
                            "        NamespaceNode {{ parser: self.parser, pointer: unsafe {{ (*self.pointer).{} }} }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_node" => {
                        let name = if field.name == "type" {
                            "type_"
                        } else {
                            field.name.as_str()
                        };

                        writeln!(file, "    pub fn {}(&self) -> Node {{", name)?;
                        writeln!(
                            file,
                            "        unsafe {{ Node::new(self.parser, (*self.pointer).{}) }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_node_list" => {
                        writeln!(file, "    pub fn {}(&self) -> NodeList {{", field.name)?;
                        writeln!(
                            file,
                            "        NodeList::new(self.parser, unsafe {{ (*self.pointer).{} }})",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_keyword" => {
                        writeln!(file, "    pub fn {}(&self) -> KeywordNode {{", field.name)?;
                        writeln!(
                            file,
                            "        KeywordNode {{ parser: self.parser, pointer: unsafe {{ (*self.pointer).{} }} }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_type_name" => {
                        writeln!(file, "    pub fn {}(&self) -> TypeNameNode {{", field.name)?;
                        writeln!(
                            file,
                            "        TypeNameNode {{ parser: self.parser, pointer: unsafe {{ (*self.pointer).{} }} }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    "rbs_types_block" => {
                        writeln!(file, "    pub fn {}(&self) -> BlockTypeNode {{", field.name)?;
                        writeln!(
                            file,
                            "        BlockTypeNode {{ parser: self.parser, pointer: unsafe {{ (*self.pointer).{} }} }}",
                            field.c_name()
                        )?;
                        writeln!(file, "    }}")?;
                    }
                    _ => eprintln!("Unknown field type: {}", field.c_type),
                }
            }
        }
        writeln!(file, "}}\n")?;
    }

    // Generate the Node enum to wrap all of the structs
    writeln!(file, "#[derive(Debug)]")?;
    writeln!(file, "pub enum Node {{")?;
    for node in &config.nodes {
        let variant_name = node
            .rust_name
            .strip_suffix("Node")
            .unwrap_or(&node.rust_name);

        writeln!(file, "    {}({}),", variant_name, node.rust_name)?;
    }
    writeln!(file, "}}")?;

    writeln!(file, "impl Node {{")?;
    writeln!(file, "    #[allow(clippy::missing_safety_doc)]")?;
    writeln!(
        file,
        "    pub unsafe fn new(parser: *mut rbs_parser_t, node: *mut rbs_node_t) -> Self {{"
    )?;
    writeln!(file, "        match unsafe {{ (*node).type_ }} {{")?;
    for node in &config.nodes {
        let variant_name = node
            .rust_name
            .strip_suffix("Node")
            .unwrap_or(&node.rust_name);

        let enum_name = convert_name(&node.name, CIdentifier::Constant);

        writeln!(
            file,
            "            rbs_node_type::{} => Self::{}({} {{ parser, pointer: node.cast::<{}>() }}),",
            enum_name,
            variant_name,
            node.rust_name,
            convert_name(&node.name, CIdentifier::Type)
        )?;
    }
    writeln!(
        file,
        "            _ => panic!(\"Unknown node type: {{}}\", unsafe {{ (*node).type_ }})"
    )?;
    writeln!(file, "        }}")?;
    writeln!(file, "    }}")?;
    writeln!(file, "}}")?;

    Ok(())
}
