module RBS
  module Prototype
    module CommentParser
      def build_comments_prism: (Array[Prism::Comment] comments, include_trailing: bool) -> Hash[Integer, AST::Comment]

      def parse_comments: (String, include_trailing: bool) -> Hash[Integer, AST::Comment]
    end

    module RubyVMHelpers
      type node = RubyVM::AbstractSyntaxTree::Node

      def block_from_body: (node) -> Types::Block?

      def each_node: (Array[untyped] nodes) { (node) -> void } -> void

      def each_child: (node) { (node child) -> void } -> void

      def any_node?: (node, ?nodes: Array[node]) { (node) -> bool } -> Array[node]?

      def keyword_hash?: (node) -> bool

      def symbol_literal_node?: (node) -> Symbol?

      def args_from_node: (node?) -> Array[untyped]

      def untyped: () -> Types::Bases::Any

      @untyped: Types::Bases::Any
    end
  end
end
