module RBS
  module Prototype
    class NodeUsage
      include Helpers

      @node: Prism::Node

      attr_reader conditional_nodes: Set[Prism::Node]

      def initialize: (Prism::Node) -> void

      def calculate: (Prism::Node, conditional: bool) -> void

      def each_conditional_node: () { (Prism::Node) -> void } -> void
                               | () -> Enumerator[Prism::Node, void]
    end
  end
end
