module RBS
  module Prototype
    module RBI
      def self.new: () -> Base

      class Base
        include CommentParser

        type module_decl = AST::Declarations::Class | AST::Declarations::Module

        attr_reader decls: Array[AST::Declarations::t]

        attr_reader modules: Array[module_decl]

        attr_reader last_sig: Array[untyped]?

        def initialize: () -> void

        def parse: (String) -> void

        def nested_name: (untyped name) -> TypeName

        def current_namespace: () -> Namespace

        def push_class: (untyped name, untyped super_class, comment: AST::Comment?) { () -> void } -> void

        def push_module: (untyped name, comment: AST::Comment?) { () -> void } -> void

        def current_module: () -> module_decl?

        def current_module!: () -> module_decl

        def push_sig: (untyped node) -> void

        def pop_sig: () -> Array[untyped]?

        def const_to_name: (untyped node) -> TypeName
      end

      class RubyVM < Base
        include RubyVMHelpers

        type node = RubyVM::AbstractSyntaxTree::Node

        def join_comments: (Array[node], Hash[Integer, AST::Comment]) -> AST::Comment

        def process: (node, comments: Hash[Integer, AST::Comment], ?outer: Array[node]) -> void

        def method_type: (node?, node?, variables: Array[AST::TypeParam], overloads: Integer) -> MethodType?

        def parse_params: (node, node, MethodType, variables: Array[AST::TypeParam], overloads: Integer) -> MethodType

        def type_of: (node, variables: Array[AST::TypeParam]) -> Types::t

        def type_of0: (node, variables: Array[AST::TypeParam]) -> Types::t

        def proc_type?: (node) -> bool

        def call_node?: (node, name: Symbol, ?receiver: ^(node) -> bool, ?args: ^(node) -> bool) -> bool

        def each_arg: (node?) { (node) -> void } -> void
                    | (node?) -> Enumerator[node, void]

        def each_child: (node) { (node) -> void } -> void

        def node_to_hash: (node?) -> Hash[Symbol, node]?

        def untyped: () -> Types::Bases::Any

        @untyped: Types::Bases::Any
      end

      class Prism < Base
        def process: (untyped, ?outer: Array[untyped], comments: Hash[Integer, AST::Comment]) -> void

        private

        def handle_fcall: (untyped, outer: Array[untyped], comments: Hash[Integer, AST::Comment]) -> void

        def handle_sig: (untyped) -> void

        def join_comments: (Array[untyped], Hash[Integer, AST::Comment]) -> AST::Comment

        def method_type: (Prism::DefNode?, untyped, variables: Array[AST::TypeParam], overloads: Integer) -> MethodType?

        def walk_sig_chain: (Prism::DefNode?, untyped, MethodType, variables: Array[AST::TypeParam], overloads: Integer) -> MethodType

        def parse_params: (Prism::DefNode, Array[untyped], MethodType, variables: Array[AST::TypeParam], overloads: Integer) -> MethodType

        def args_to_hash: (untyped, variables: Array[AST::TypeParam]) -> Hash[Symbol, Types::t]

        def type_of: (untyped, variables: Array[AST::TypeParam]) -> Types::t

        def type_of0: (untyped, variables: Array[AST::TypeParam]) -> Types::t

        def t_call?: (untyped) -> bool

        def handle_t_call: (untyped, variables: Array[AST::TypeParam]) -> Types::t

        def proc_type?: (untyped) -> bool

        def handle_cdecl: (Prism::ConstantWriteNode) -> void

        def symbol_value: (untyped) -> Symbol?
      end
    end
  end
end
