%a{annotate:rdoc:skip}
module TSort[N]
  interface _Sortable[N]
    # #tsort_each_node is used to iterate for all nodes over a graph.
    #
    def tsort_each_node: () { (N) -> void } -> void

    # #tsort_each_child is used to iterate for child nodes of node.
    #
    def tsort_each_child: (N) { (N) -> void } -> void
  end

  interface _EachNode[N]
    def call: () { (N) -> void } -> void
  end

  interface _EachChild[N]
    def call: (N) { (N) -> void } -> void
  end
end
