interface _ToI
  def to_i: -> Integer
end

interface _ToInt
  def to_int: -> Integer
end

interface _ToS
  def to_s: -> String
end

interface _ToStr
  def to_str: () -> String
end

interface _Each[out A, out B]
  def each: { (A) -> void } -> B
end

class BigDecimal
end
