# The class of the singleton object `nil` .
class NilClass < Object
  def &: (untyped obj) -> false

  def ^: (untyped obj) -> bool

  # Returns zero as a rational. The optional argument `eps` is always
  # ignored.
  def rationalize: () -> Rational

  # Always returns an empty array.
  # 
  # ```ruby
  # nil.to_a   #=> []
  # ```
  def to_a: () -> untyped

  # Returns zero as a complex.
  def to_c: () -> Complex

  # Always returns zero.
  # 
  # ```ruby
  # nil.to_f   #=> 0.0
  # ```
  def to_f: () -> Float

  # Always returns an empty hash.
  # 
  # ```ruby
  # nil.to_h   #=> {}
  # ```
  def to_h: () -> ::Hash[untyped, untyped]

  # Always returns zero.
  # 
  # ```ruby
  # nil.to_i   #=> 0
  # ```
  def to_i: () -> 0

  # Returns zero as a rational.
  def to_r: () -> Rational

  def |: (untyped obj) -> bool

  # Only the object *nil* responds `true` to `nil?` .
  def `nil?`: () -> true
end
