class ERB
  def self.version: () -> String

  def initialize: (String, ?trim_mode: Integer | String | NilClass, ?eoutvar: String) -> untyped
  def src: () -> String
  def encoding: () -> Encoding
  def filename: () -> (String | NilClass)
  def filename=: (String | NilClass) -> untyped
  def lineno: () -> Integer
  def lineno=: (Integer) -> untyped
  def location=: (Array[String | Integer]) -> untyped
  def run: (?Binding) -> untyped
  def result: (?Binding) -> String
  def result_with_hash: (Hash[untyped, untyped]) -> String
  def def_method: (Module, String, ?String) -> untyped
  def def_module: (?String) -> Module
  def def_class: (?Class, ?String) -> Class
end
