module RBS
  # Locator helps finding RBS elements based on locations in the RBS source text.
  #
  class Locator
    type component = Symbol
                   | Types::t
                   | MethodType
                   | AST::Declarations::t
                   | AST::Members::t
                   | AST::TypeParam
                   | AST::Declarations::Class::Super
                   | AST::Declarations::Module::Self
                   | AST::Directives::t
                   | AST::Directives::Use::clause

    # The buffer the location points to
    #
    attr_reader buffer: Buffer

    # Array of _top-level_ declarations.
    #
    attr_reader decls: Array[AST::Declarations::t]

    # Array of directives.
    #
    attr_reader dirs: Array[AST::Directives::t]

    def initialize: (buffer: Buffer, decls: Array[AST::Declarations::t], dirs: Array[AST::Directives::t]) -> void

    # Find RBS elements at the given position.
    # Returns a list of components, inner component comes first.
    #
    # `line` is the line number (1-origin).
    # `byte_column` is the byte offset within the line (0-origin).
    # `char_column` is the character offset within the line (0-origin), converted to byte offset internally.
    #
    def find: (line: Integer, byte_column: Integer) -> Array[component]
            | (line: Integer, char_column: Integer) -> Array[component]
            | %a{deprecated: use char_column or byte_column instead} (line: Integer, column: Integer) -> Array[component]

    # Find RBS elements at the given position, returning the inner most symbol and outer components.
    # It ensures the array starts with a AST/type component.
    #
    # `line` is the line number (1-origin).
    # `byte_column` is the byte offset within the line (0-origin).
    # `char_column` is the character offset within the line (0-origin), converted to byte offset internally.
    #
    def find2: (line: Integer, byte_column: Integer) -> [Symbol?, Array[component]]?
             | (line: Integer, char_column: Integer) -> [Symbol?, Array[component]]?
             | %a{deprecated: use char_column or byte_column instead} (line: Integer, column: Integer) -> [Symbol?, Array[component]]?

    def find_in_directive: (Integer pos, AST::Directives::t, Array[component]) -> bool

    def find_in_decl: (Integer pos, decl: AST::Declarations::t, array: Array[component]) -> bool

    def find_in_member: (Integer pos, member: AST::Members::t, array: Array[component]) -> bool

    def find_in_method_type: (Integer pos, method_type: MethodType, array: Array[component]) -> bool

    def find_in_type: (Integer pos, type: Types::t, array: Array[component]) -> bool

    def find_in_type_param: (Integer pos, type_param: AST::TypeParam, array: Array[component]) -> bool

    def find_in_loc: (Integer pos, location: Location[untyped, untyped]?, array: Array[component]) -> bool

    def test_loc: (Integer pos, location: Location[untyped, untyped]?) -> bool

    private

    # Converts a character column offset to a byte column offset within the given line.
    #
    def char_column_to_byte_column: (Integer line, Integer char_column) -> Integer

    # Resolves line and column arguments to a byte position in the buffer.
    # Exactly one of `byte_column`, `char_column`, or `column` must be given.
    #
    def resolve_position: (line: Integer, column: Integer?, byte_column: Integer?, char_column: Integer?) -> Integer
  end
end
