module RBS
  class MethodType
    attr_reader type_params: Array[AST::TypeParam]
    attr_reader type: Types::Function
    attr_reader block: Types::Block?
    attr_reader location: Location[untyped, untyped]?

    def initialize: (type_params: Array[AST::TypeParam], type: Types::Function, block: Types::Block?, location: Location[untyped, untyped]?) -> void

    def ==: (untyped other) -> bool

    include _ToJson

    def sub: (Substitution) -> MethodType

    def update: (?type_params: Array[AST::TypeParam], ?type: Types::Function, ?block: Types::Block?, ?location: Location[untyped, untyped]?) -> MethodType

    def free_variables: (?Set[Symbol] set) -> Set[Symbol]

    def map_type: () { (Types::t) -> Types::t } -> MethodType

    def each_type: () { (Types::t) -> void } -> void
                 | () -> Enumerator[Types::t, void]

    def to_s: () -> String

    def type_param_names: () -> Array[Symbol]
  end
end
