module RBS
  class Subtractor
    @minuend: Array[AST::Declarations::t]
    @subtrahend: Environment

    def initialize: (Array[AST::Declarations::t] minuend, Environment subtrahend) -> void

    def call: () -> Array[AST::Declarations::t]
  end
end
