class Set[A]
  def self.`[]`: [X] (*X) -> Set[X]

  def initialize: (_Each[A, untyped]) -> untyped
                | [X] (_Each[X, untyped]) { (X) -> A } -> untyped
                | (?nil) -> untyped

  def intersection: (_Each[A, untyped]) -> self
  def &: (_Each[A, untyped]) -> self

  def union: (_Each[A, untyped]) -> self
  def `+`: (_Each[A, untyped]) -> self
  def `|`: (_Each[A, untyped]) -> self

  def difference: (_Each[A, untyped]) -> self
  def `-`: (_Each[A, untyped]) -> self

  def add: (A) -> self
  def `<<`: (A) -> self
  def add?: (A) -> self?

  def member?: (untyped) -> bool
  def include?: (untyped) -> bool

  def `^`: (_Each[A, untyped]) -> self

  def classify: [X] { (A) -> X } -> Hash[X, self]

  def clear: -> self

  def collect!: { (A) -> A } -> self
  alias map! collect!

  def delete: (untyped) -> self
  def delete?: (untyped) -> self?

  def delete_if: { (A) -> untyped } -> self
  def reject!: { (A) -> untyped } -> self

  def disjoint?: (self) -> bool

  def divide: { (A, A) -> untyped } -> Set[self]
            | { (A) -> untyped } -> Set[self]

  def each: { (A) -> void } -> self

  def empty?: -> bool

  def flatten: -> Set[untyped]

  def intersect?: -> bool

  def keep_if: { (A) -> untyped } -> self

  def size: -> Integer
  alias length size

  def merge: (_Each[A, untyped]) -> self

  def subset?: (self) -> bool
  def proper_subst?: (self) -> bool

  def superset?: (self) -> bool
  def proper_superset?: (self) -> bool

  def replace: (_Each[A, untyped]) -> self

  def reset: -> self

  def select!: { (A) -> untyped } -> self?

  def subtract: (_Each[A, untyped]) -> self

  def to_a: -> Array[A]

  include Enumerable[A, self]
end
