module RBS
  class CLI
    class Diff
      @stdout: _IO
      @stderr: _IO

      def initialize: (?stdout: _IO, ?stderr: _IO) -> void

      def run: (library_options: RBS::CLI::LibraryOptions, argv: Array[String]) -> Integer

      def run_diff: (RBS::Diff) -> void
      def run_markdown: (RBS::Diff) -> void
    end
  end
end
