module CMath
  include Math

  RealMath: untyped

  def exp: (untyped z) -> untyped

  def log: (untyped z, ?untyped b) -> untyped

  def log2: (untyped z) -> untyped

  def log10: (untyped z) -> untyped

  def sqrt: (untyped z) -> untyped

  def cbrt: (untyped z) -> untyped

  def sin: (untyped z) -> untyped

  def cos: (untyped z) -> untyped

  def tan: (untyped z) -> untyped

  def sinh: (untyped z) -> untyped

  def cosh: (untyped z) -> untyped

  def tanh: (untyped z) -> untyped

  def asin: (untyped z) -> untyped

  def acos: (untyped z) -> untyped

  def atan: (untyped z) -> untyped

  def atan2: (untyped y, untyped x) -> untyped

  def asinh: (untyped z) -> untyped

  def acosh: (untyped z) -> untyped

  def atanh: (untyped z) -> untyped

  def handle_no_method_error: () -> untyped
end
