require_relative "test_helper"

class ErrnoTest < StdlibTest
  target Errno

  def test_all_constants
    Errno::NOERROR::Errno
    Errno::E2BIG::Errno
    Errno::EACCES::Errno
    Errno::EADDRINUSE::Errno
    Errno::EADDRNOTAVAIL::Errno
    Errno::EADV::Errno
    Errno::EAFNOSUPPORT::Errno
    Errno::EAGAIN::Errno
    Errno::EALREADY::Errno
    Errno::EAUTH::Errno
    Errno::EBADARCH::Errno
    Errno::EBADE::Errno
    Errno::EBADEXEC::Errno
    Errno::EBADF::Errno
    Errno::EBADFD::Errno
    Errno::EBADMACHO::Errno
    Errno::EBADMSG::Errno
    Errno::EBADR::Errno
    Errno::EBADRPC::Errno
    Errno::EBADRQC::Errno
    Errno::EBADSLT::Errno
    Errno::EBFONT::Errno
    Errno::EBUSY::Errno
    Errno::ECANCELED::Errno
    Errno::ECAPMODE::Errno
    Errno::ECHILD::Errno
    Errno::ECHRNG::Errno
    Errno::ECOMM::Errno
    Errno::ECONNABORTED::Errno
    Errno::ECONNREFUSED::Errno
    Errno::ECONNRESET::Errno
    Errno::EDEADLK::Errno
    Errno::EDEADLOCK::Errno
    Errno::EDESTADDRREQ::Errno
    Errno::EDEVERR::Errno
    Errno::EDOM::Errno
    Errno::EDOOFUS::Errno
    Errno::EDOTDOT::Errno
    Errno::EDQUOT::Errno
    Errno::EEXIST::Errno
    Errno::EFAULT::Errno
    Errno::EFBIG::Errno
    Errno::EFTYPE::Errno
    Errno::EHOSTDOWN::Errno
    Errno::EHOSTUNREACH::Errno
    Errno::EHWPOISON::Errno
    Errno::EIDRM::Errno
    Errno::EILSEQ::Errno
    Errno::EINPROGRESS::Errno
    Errno::EINTR::Errno
    Errno::EINVAL::Errno
    Errno::EIO::Errno
    Errno::EIPSEC::Errno
    Errno::EISCONN::Errno
    Errno::EISDIR::Errno
    Errno::EISNAM::Errno
    Errno::EKEYEXPIRED::Errno
    Errno::EKEYREJECTED::Errno
    Errno::EKEYREVOKED::Errno
    Errno::EL2HLT::Errno
    Errno::EL2NSYNC::Errno
    Errno::EL3HLT::Errno
    Errno::EL3RST::Errno
    Errno::ELAST::Errno
    Errno::ELIBACC::Errno
    Errno::ELIBBAD::Errno
    Errno::ELIBEXEC::Errno
    Errno::ELIBMAX::Errno
    Errno::ELIBSCN::Errno
    Errno::ELNRNG::Errno
    Errno::ELOOP::Errno
    Errno::EMEDIUMTYPE::Errno
    Errno::EMFILE::Errno
    Errno::EMLINK::Errno
    Errno::EMSGSIZE::Errno
    Errno::EMULTIHOP::Errno
    Errno::ENAMETOOLONG::Errno
    Errno::ENAVAIL::Errno
    Errno::ENEEDAUTH::Errno
    Errno::ENETDOWN::Errno
    Errno::ENETRESET::Errno
    Errno::ENETUNREACH::Errno
    Errno::ENFILE::Errno
    Errno::ENOANO::Errno
    Errno::ENOATTR::Errno
    Errno::ENOBUFS::Errno
    Errno::ENOCSI::Errno
    Errno::ENODATA::Errno
    Errno::ENODEV::Errno
    Errno::ENOENT::Errno
    Errno::ENOEXEC::Errno
    Errno::ENOKEY::Errno
    Errno::ENOLCK::Errno
    Errno::ENOLINK::Errno
    Errno::ENOMEDIUM::Errno
    Errno::ENOMEM::Errno
    Errno::ENOMSG::Errno
    Errno::ENONET::Errno
    Errno::ENOPKG::Errno
    Errno::ENOPOLICY::Errno
    Errno::ENOPROTOOPT::Errno
    Errno::ENOSPC::Errno
    Errno::ENOSR::Errno
    Errno::ENOSTR::Errno
    Errno::ENOSYS::Errno
    Errno::ENOTBLK::Errno
    Errno::ENOTCAPABLE::Errno
    Errno::ENOTCONN::Errno
    Errno::ENOTDIR::Errno
    Errno::ENOTEMPTY::Errno
    Errno::ENOTNAM::Errno
    Errno::ENOTRECOVERABLE::Errno
    Errno::ENOTSOCK::Errno
    Errno::ENOTSUP::Errno
    Errno::ENOTTY::Errno
    Errno::ENOTUNIQ::Errno
    Errno::ENXIO::Errno
    Errno::EOPNOTSUPP::Errno
    Errno::EOVERFLOW::Errno
    Errno::EOWNERDEAD::Errno
    Errno::EPERM::Errno
    Errno::EPFNOSUPPORT::Errno
    Errno::EPIPE::Errno
    Errno::EPROCLIM::Errno
    Errno::EPROCUNAVAIL::Errno
    Errno::EPROGMISMATCH::Errno
    Errno::EPROGUNAVAIL::Errno
    Errno::EPROTO::Errno
    Errno::EPROTONOSUPPORT::Errno
    Errno::EPROTOTYPE::Errno
    Errno::EPWROFF::Errno
    Errno::EQFULL::Errno
    Errno::ERANGE::Errno
    Errno::EREMCHG::Errno
    Errno::EREMOTE::Errno
    Errno::EREMOTEIO::Errno
    Errno::ERESTART::Errno
    Errno::ERFKILL::Errno
    Errno::EROFS::Errno
    Errno::ERPCMISMATCH::Errno
    Errno::ESHLIBVERS::Errno
    Errno::ESHUTDOWN::Errno
    Errno::ESOCKTNOSUPPORT::Errno
    Errno::ESPIPE::Errno
    Errno::ESRCH::Errno
    Errno::ESRMNT::Errno
    Errno::ESTALE::Errno
    Errno::ESTRPIPE::Errno
    Errno::ETIME::Errno
    Errno::ETIMEDOUT::Errno
    Errno::ETOOMANYREFS::Errno
    Errno::ETXTBSY::Errno
    Errno::EUCLEAN::Errno
    Errno::EUNATCH::Errno
    Errno::EUSERS::Errno
    Errno::EWOULDBLOCK::Errno
    Errno::EXDEV::Errno
    Errno::EXFULL::Errno
  end
end
