/* Generated by re2c 3.1 */
#line 1 "ext/rbs_extension/lexer.re"
#include "rbs_extension.h"

token rbsparser_next_token(lexstate *state) {
  lexstate backup;

  backup = *state;

  
#line 12 "ext/rbs_extension/lexer.c"
{
	unsigned int yych;
	unsigned int yyaccept = 0;
	yych = peek(state);
	switch (yych) {
		case 0x00000000: goto yy1;
		case '\t':
		case ' ': goto yy4;
		case '\n':
		case '\r': goto yy6;
		case '!': goto yy7;
		case '"': goto yy9;
		case '#': goto yy10;
		case '$': goto yy12;
		case '%': goto yy13;
		case '&': goto yy14;
		case '\'': goto yy15;
		case '(': goto yy16;
		case ')': goto yy17;
		case '*': goto yy18;
		case '+': goto yy19;
		case ',': goto yy20;
		case '-': goto yy21;
		case '.': goto yy22;
		case '/':
		case '~': goto yy24;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		case ':': goto yy27;
		case '<': goto yy29;
		case '=': goto yy31;
		case '>': goto yy33;
		case '?': goto yy34;
		case '@': goto yy35;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z': goto yy36;
		case '[': goto yy38;
		case ']': goto yy39;
		case '^': goto yy40;
		case '_': goto yy41;
		case '`': goto yy43;
		case 'a': goto yy45;
		case 'b': goto yy47;
		case 'c': goto yy48;
		case 'd': goto yy49;
		case 'e': goto yy50;
		case 'f': goto yy51;
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'q':
		case 'r':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy52;
		case 'i': goto yy54;
		case 'm': goto yy55;
		case 'n': goto yy56;
		case 'o': goto yy57;
		case 'p': goto yy58;
		case 's': goto yy59;
		case 't': goto yy60;
		case 'u': goto yy61;
		case 'v': goto yy62;
		case '{': goto yy63;
		case '|': goto yy64;
		case '}': goto yy65;
		default: goto yy2;
	}
yy1:
	rbs_skip(state);
#line 147 "ext/rbs_extension/lexer.re"
	{ return next_eof_token(state); }
#line 121 "ext/rbs_extension/lexer.c"
yy2:
	rbs_skip(state);
yy3:
#line 148 "ext/rbs_extension/lexer.re"
	{ return next_token(state, ErrorToken); }
#line 127 "ext/rbs_extension/lexer.c"
yy4:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '\t') goto yy4;
	if (yych == ' ') goto yy4;
yy5:
#line 146 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tTRIVIA); }
#line 136 "ext/rbs_extension/lexer.c"
yy6:
	rbs_skip(state);
	goto yy5;
yy7:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '=') goto yy24;
	if (yych == '~') goto yy24;
yy8:
#line 48 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tOPERATOR); }
#line 148 "ext/rbs_extension/lexer.c"
yy9:
	yyaccept = 0;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych <= 0x00000000) goto yy3;
	goto yy67;
yy10:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 0x00000000) goto yy11;
	if (yych != '\n') goto yy10;
yy11:
#line 60 "ext/rbs_extension/lexer.re"
	{
        return next_token(
          state,
          state->first_token_of_line ? tLINECOMMENT : tCOMMENT
        );
      }
#line 169 "ext/rbs_extension/lexer.c"
yy12:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= ')') {
		if (yych <= 0x0000001F) {
			if (yych <= '\n') {
				if (yych <= 0x00000000) goto yy3;
				if (yych <= 0x00000008) goto yy71;
				goto yy3;
			} else {
				if (yych == '\r') goto yy3;
				goto yy71;
			}
		} else {
			if (yych <= '#') {
				if (yych <= ' ') goto yy3;
				if (yych <= '"') goto yy73;
				goto yy71;
			} else {
				if (yych == '%') goto yy3;
				if (yych <= '\'') goto yy73;
				goto yy3;
			}
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '/') {
				if (yych == '-') goto yy71;
				goto yy73;
			} else {
				if (yych <= '9') goto yy71;
				if (yych <= '>') goto yy73;
				goto yy71;
			}
		} else {
			if (yych <= '^') {
				if (yych == '\\') goto yy73;
				goto yy3;
			} else {
				if (yych <= 'z') goto yy71;
				if (yych <= '}') goto yy3;
				if (yych <= '~') goto yy73;
				goto yy71;
			}
		}
	}
yy13:
	yyaccept = 1;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych == 'a') goto yy74;
	goto yy8;
yy14:
	rbs_skip(state);
#line 33 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pAMP); }
#line 227 "ext/rbs_extension/lexer.c"
yy15:
	yyaccept = 0;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych <= 0x00000000) goto yy3;
	goto yy76;
yy16:
	rbs_skip(state);
#line 24 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pLPAREN); }
#line 239 "ext/rbs_extension/lexer.c"
yy17:
	rbs_skip(state);
#line 25 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pRPAREN); }
#line 244 "ext/rbs_extension/lexer.c"
yy18:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '*') goto yy80;
#line 35 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pSTAR); }
#line 251 "ext/rbs_extension/lexer.c"
yy19:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '/') goto yy8;
	if (yych <= '9') goto yy25;
	if (yych == '@') goto yy24;
	goto yy8;
yy20:
	rbs_skip(state);
#line 30 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pCOMMA); }
#line 263 "ext/rbs_extension/lexer.c"
yy21:
	rbs_skip(state);
	yych = peek(state);
	switch (yych) {
		case '-': goto yy81;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		case '>': goto yy82;
		case '@': goto yy24;
		default: goto yy8;
	}
yy22:
	yyaccept = 2;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych == '.') goto yy83;
yy23:
#line 37 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pDOT); }
#line 292 "ext/rbs_extension/lexer.c"
yy24:
	rbs_skip(state);
	goto yy8;
yy25:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '/') goto yy26;
	if (yych <= '9') goto yy25;
	if (yych == '_') goto yy25;
yy26:
#line 52 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tINTEGER); }
#line 305 "ext/rbs_extension/lexer.c"
yy27:
	yyaccept = 3;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	switch (yych) {
		case '!': goto yy84;
		case '"': goto yy86;
		case '$': goto yy87;
		case '%':
		case '&':
		case '/':
		case '^':
		case '`':
		case '|':
		case '~': goto yy88;
		case '\'': goto yy89;
		case '*': goto yy90;
		case '+':
		case '-': goto yy91;
		case ':': goto yy92;
		case '<': goto yy93;
		case '=': goto yy94;
		case '>': goto yy95;
		case '@': goto yy96;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy97;
		case '[': goto yy99;
		default: goto yy28;
	}
yy28:
#line 44 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pCOLON); }
#line 390 "ext/rbs_extension/lexer.c"
yy29:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= ';') goto yy30;
	if (yych <= '<') goto yy24;
	if (yych <= '=') goto yy100;
yy30:
#line 46 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pLT); }
#line 400 "ext/rbs_extension/lexer.c"
yy31:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '>') {
		if (yych <= '<') goto yy32;
		if (yych <= '=') goto yy101;
		goto yy102;
	} else {
		if (yych == '~') goto yy24;
	}
yy32:
#line 43 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pEQ); }
#line 414 "ext/rbs_extension/lexer.c"
yy33:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '<') goto yy8;
	if (yych <= '>') goto yy24;
	goto yy8;
yy34:
	rbs_skip(state);
#line 34 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pQUESTION); }
#line 425 "ext/rbs_extension/lexer.c"
yy35:
	yyaccept = 0;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych <= '_') {
		if (yych <= '@') {
			if (yych <= '?') goto yy3;
			goto yy103;
		} else {
			if (yych <= 'Z') goto yy104;
			if (yych <= '^') goto yy3;
			goto yy104;
		}
	} else {
		if (yych <= 'q') {
			if (yych <= '`') goto yy3;
			goto yy104;
		} else {
			if (yych <= 'r') goto yy107;
			if (yych <= 'z') goto yy104;
			goto yy3;
		}
	}
yy36:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy36;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy37;
			if (yych <= 'Z') goto yy36;
		} else {
			if (yych == '`') goto yy37;
			if (yych <= 'z') goto yy36;
		}
	}
yy37:
#line 132 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tUIDENT); }
#line 472 "ext/rbs_extension/lexer.c"
yy38:
	rbs_skip(state);
	yych = peek(state);
	if (yych == ']') goto yy110;
#line 26 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pLBRACKET); }
#line 479 "ext/rbs_extension/lexer.c"
yy39:
	rbs_skip(state);
#line 27 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pRBRACKET); }
#line 484 "ext/rbs_extension/lexer.c"
yy40:
	rbs_skip(state);
#line 32 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pHAT); }
#line 489 "ext/rbs_extension/lexer.c"
yy41:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy111;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy42;
			if (yych <= 'Z') goto yy114;
		} else {
			if (yych <= '_') goto yy116;
			if (yych <= '`') goto yy42;
			if (yych <= 'z') goto yy111;
		}
	}
yy42:
#line 135 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tULLIDENT); }
#line 513 "ext/rbs_extension/lexer.c"
yy43:
	yyaccept = 4;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych <= ' ') {
		if (yych <= 0x00000000) goto yy44;
		if (yych <= 0x0000001F) goto yy117;
	} else {
		if (yych != ':') goto yy117;
	}
yy44:
#line 39 "ext/rbs_extension/lexer.re"
	{  return next_token(state, tOPERATOR); }
#line 528 "ext/rbs_extension/lexer.c"
yy45:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 'r') {
		if (yych == 'l') goto yy118;
		goto yy53;
	} else {
		if (yych <= 's') goto yy119;
		if (yych <= 't') goto yy121;
		goto yy53;
	}
yy46:
#line 131 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tLIDENT); }
#line 543 "ext/rbs_extension/lexer.c"
yy47:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy122;
	goto yy53;
yy48:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy123;
	goto yy53;
yy49:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy124;
	goto yy53;
yy50:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy125;
	if (yych == 'x') goto yy126;
	goto yy53;
yy51:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'a') goto yy127;
	goto yy53;
yy52:
	rbs_skip(state);
	yych = peek(state);
yy53:
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
			goto yy46;
		} else {
			if (yych <= '9') goto yy52;
			if (yych <= '<') goto yy46;
			goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy46;
			if (yych <= 'Z') goto yy52;
			goto yy46;
		} else {
			if (yych == '`') goto yy46;
			if (yych <= 'z') goto yy52;
			goto yy46;
		}
	}
yy54:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy128;
	goto yy53;
yy55:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy130;
	goto yy53;
yy56:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'i') goto yy131;
	goto yy53;
yy57:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'u') goto yy132;
	goto yy53;
yy58:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'r') goto yy133;
	if (yych == 'u') goto yy134;
	goto yy53;
yy59:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 'h') {
		if (yych == 'e') goto yy135;
		goto yy53;
	} else {
		if (yych <= 'i') goto yy136;
		if (yych == 'k') goto yy137;
		goto yy53;
	}
yy60:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 'q') {
		if (yych == 'o') goto yy138;
		goto yy53;
	} else {
		if (yych <= 'r') goto yy139;
		if (yych == 'y') goto yy140;
		goto yy53;
	}
yy61:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy141;
	if (yych == 's') goto yy142;
	goto yy53;
yy62:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy143;
	goto yy53;
yy63:
	rbs_skip(state);
#line 28 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pLBRACE); }
#line 657 "ext/rbs_extension/lexer.c"
yy64:
	rbs_skip(state);
#line 31 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pBAR); }
#line 662 "ext/rbs_extension/lexer.c"
yy65:
	rbs_skip(state);
#line 29 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pRBRACE); }
#line 667 "ext/rbs_extension/lexer.c"
yy66:
	rbs_skip(state);
	yych = peek(state);
yy67:
	if (yych <= '"') {
		if (yych <= 0x00000000) goto yy68;
		if (yych <= '!') goto yy66;
		goto yy69;
	} else {
		if (yych == '\\') goto yy70;
		goto yy66;
	}
yy68:
	*state = backup;
	if (yyaccept <= 3) {
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy3;
			} else {
				goto yy8;
			}
		} else {
			if (yyaccept == 2) {
				goto yy23;
			} else {
				goto yy28;
			}
		}
	} else {
		if (yyaccept <= 5) {
			if (yyaccept == 4) {
				goto yy44;
			} else {
				goto yy78;
			}
		} else {
			goto yy159;
		}
	}
yy69:
	rbs_skip(state);
#line 109 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tDQSTRING); }
#line 711 "ext/rbs_extension/lexer.c"
yy70:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'u') goto yy144;
	if (yych == 'x') goto yy145;
	goto yy66;
yy71:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= ',') {
		if (yych <= '\f') {
			if (yych <= 0x00000000) goto yy72;
			if (yych <= 0x00000008) goto yy71;
			if (yych >= '\v') goto yy71;
		} else {
			if (yych <= 0x0000001F) {
				if (yych >= 0x0000000E) goto yy71;
			} else {
				if (yych == '#') goto yy71;
			}
		}
	} else {
		if (yych <= '>') {
			if (yych <= '-') goto yy71;
			if (yych <= '/') goto yy72;
			if (yych <= '9') goto yy71;
		} else {
			if (yych <= '^') {
				if (yych <= 'Z') goto yy71;
			} else {
				if (yych <= 'z') goto yy71;
				if (yych >= 0x0000007F) goto yy71;
			}
		}
	}
yy72:
#line 142 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tGIDENT); }
#line 750 "ext/rbs_extension/lexer.c"
yy73:
	rbs_skip(state);
	goto yy72;
yy74:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 'Z') {
		if (yych <= '(') {
			if (yych <= '\'') goto yy68;
			goto yy146;
		} else {
			if (yych == '<') goto yy147;
			goto yy68;
		}
	} else {
		if (yych <= 'z') {
			if (yych <= '[') goto yy148;
			goto yy68;
		} else {
			if (yych <= '{') goto yy149;
			if (yych <= '|') goto yy150;
			goto yy68;
		}
	}
yy75:
	rbs_skip(state);
	yych = peek(state);
yy76:
	if (yych <= '\'') {
		if (yych <= 0x00000000) goto yy68;
		if (yych <= '&') goto yy75;
	} else {
		if (yych == '\\') goto yy79;
		goto yy75;
	}
yy77:
	rbs_skip(state);
yy78:
#line 110 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tSQSTRING); }
#line 791 "ext/rbs_extension/lexer.c"
yy79:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '\'') {
		if (yych <= 0x00000000) goto yy68;
		if (yych <= '&') goto yy75;
		goto yy151;
	} else {
		if (yych == '\\') goto yy79;
		goto yy75;
	}
yy80:
	rbs_skip(state);
#line 36 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pSTAR2); }
#line 807 "ext/rbs_extension/lexer.c"
yy81:
	rbs_skip(state);
	yych = peek(state);
	if (yych >= 0x00000001) goto yy81;
#line 49 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tINLINECOMMENT); }
#line 814 "ext/rbs_extension/lexer.c"
yy82:
	rbs_skip(state);
#line 41 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pARROW); }
#line 819 "ext/rbs_extension/lexer.c"
yy83:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '.') goto yy152;
	goto yy68;
yy84:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '=') goto yy88;
	if (yych == '~') goto yy88;
yy85:
#line 129 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tSYMBOL); }
#line 833 "ext/rbs_extension/lexer.c"
yy86:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '"') {
		if (yych <= 0x00000000) goto yy68;
		if (yych <= '!') goto yy86;
		goto yy153;
	} else {
		if (yych == '\\') goto yy154;
		goto yy86;
	}
yy87:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= ')') {
		if (yych <= 0x0000001F) {
			if (yych <= '\n') {
				if (yych <= 0x00000000) goto yy68;
				if (yych <= 0x00000008) goto yy155;
				goto yy68;
			} else {
				if (yych == '\r') goto yy68;
				goto yy155;
			}
		} else {
			if (yych <= '#') {
				if (yych <= ' ') goto yy68;
				if (yych <= '"') goto yy157;
				goto yy155;
			} else {
				if (yych == '%') goto yy68;
				if (yych <= '\'') goto yy157;
				goto yy68;
			}
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '/') {
				if (yych == '-') goto yy155;
				goto yy157;
			} else {
				if (yych <= '9') goto yy155;
				if (yych <= '>') goto yy157;
				goto yy155;
			}
		} else {
			if (yych <= '^') {
				if (yych == '\\') goto yy157;
				goto yy68;
			} else {
				if (yych <= 'z') goto yy155;
				if (yych <= '}') goto yy68;
				if (yych <= '~') goto yy157;
				goto yy155;
			}
		}
	}
yy88:
	rbs_skip(state);
	goto yy85;
yy89:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '\'') {
		if (yych <= 0x00000000) goto yy68;
		if (yych <= '&') goto yy89;
		goto yy158;
	} else {
		if (yych == '\\') goto yy160;
		goto yy89;
	}
yy90:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '*') goto yy88;
	goto yy85;
yy91:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '@') goto yy88;
	goto yy85;
yy92:
	rbs_skip(state);
#line 45 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pCOLON2); }
#line 919 "ext/rbs_extension/lexer.c"
yy93:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= ';') goto yy85;
	if (yych <= '<') goto yy88;
	if (yych <= '=') goto yy161;
	goto yy85;
yy94:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '=') goto yy162;
	if (yych == '~') goto yy88;
	goto yy68;
yy95:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '<') goto yy85;
	if (yych <= '>') goto yy88;
	goto yy85;
yy96:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '^') {
		if (yych <= '?') goto yy68;
		if (yych <= '@') goto yy163;
		if (yych <= 'Z') goto yy164;
		goto yy68;
	} else {
		if (yych == '`') goto yy68;
		if (yych <= 'z') goto yy164;
		goto yy68;
	}
yy97:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '>') {
		if (yych <= '/') {
			if (yych == '!') goto yy166;
		} else {
			if (yych <= '9') goto yy97;
			if (yych == '=') goto yy166;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '?') goto yy166;
			if (yych <= '@') goto yy98;
			if (yych <= 'Z') goto yy97;
		} else {
			if (yych == '`') goto yy98;
			if (yych <= 'z') goto yy97;
		}
	}
yy98:
#line 125 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tSYMBOL); }
#line 975 "ext/rbs_extension/lexer.c"
yy99:
	rbs_skip(state);
	yych = peek(state);
	if (yych == ']') goto yy162;
	goto yy68;
yy100:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '>') goto yy24;
	goto yy8;
yy101:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '=') goto yy24;
	goto yy8;
yy102:
	rbs_skip(state);
#line 42 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pFATARROW); }
#line 995 "ext/rbs_extension/lexer.c"
yy103:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '^') {
		if (yych <= '@') goto yy68;
		if (yych <= 'Z') goto yy167;
		goto yy68;
	} else {
		if (yych == '`') goto yy68;
		if (yych <= 'z') goto yy167;
		goto yy68;
	}
yy104:
	rbs_skip(state);
	yych = peek(state);
yy105:
	if (yych <= 'Z') {
		if (yych <= '/') goto yy106;
		if (yych <= '9') goto yy104;
		if (yych >= 'A') goto yy104;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy104;
		} else {
			if (yych <= '`') goto yy106;
			if (yych <= 'z') goto yy104;
		}
	}
yy106:
#line 139 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tAIDENT); }
#line 1027 "ext/rbs_extension/lexer.c"
yy107:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'b') goto yy169;
	goto yy105;
yy108:
	rbs_skip(state);
#line 136 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tBANGIDENT); }
#line 1037 "ext/rbs_extension/lexer.c"
yy109:
	rbs_skip(state);
#line 137 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tEQIDENT); }
#line 1042 "ext/rbs_extension/lexer.c"
yy110:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '=') goto yy24;
#line 47 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pAREF_OPR); }
#line 1049 "ext/rbs_extension/lexer.c"
yy111:
	rbs_skip(state);
	yych = peek(state);
yy112:
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy111;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy113;
			if (yych <= 'Z') goto yy111;
		} else {
			if (yych == '`') goto yy113;
			if (yych <= 'z') goto yy111;
		}
	}
yy113:
#line 133 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tULLIDENT); }
#line 1073 "ext/rbs_extension/lexer.c"
yy114:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy114;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy115;
			if (yych <= 'Z') goto yy114;
		} else {
			if (yych == '`') goto yy115;
			if (yych <= 'z') goto yy114;
		}
	}
yy115:
#line 134 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tULIDENT); }
#line 1096 "ext/rbs_extension/lexer.c"
yy116:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy170;
	goto yy112;
yy117:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 0x00000000) goto yy68;
	if (yych == '`') goto yy171;
	goto yy117;
yy118:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'i') goto yy172;
	goto yy53;
yy119:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy120;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy120;
			if (yych <= 'z') goto yy52;
		}
	}
yy120:
#line 97 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kAS); }
#line 1135 "ext/rbs_extension/lexer.c"
yy121:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy173;
	goto yy53;
yy122:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy174;
	if (yych == 't') goto yy175;
	goto yy53;
yy123:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'a') goto yy177;
	goto yy53;
yy124:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'f') goto yy178;
	goto yy53;
yy125:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy180;
	goto yy53;
yy126:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy182;
	goto yy53;
yy127:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy183;
	goto yy53;
yy128:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '^') {
		if (yych <= '9') {
			if (yych == '!') goto yy108;
			if (yych >= '0') goto yy52;
		} else {
			if (yych <= '=') {
				if (yych >= '=') goto yy109;
			} else {
				if (yych <= '@') goto yy129;
				if (yych <= 'Z') goto yy52;
			}
		}
	} else {
		if (yych <= 'c') {
			if (yych == '`') goto yy129;
			if (yych <= 'b') goto yy52;
			goto yy184;
		} else {
			if (yych <= 's') {
				if (yych <= 'r') goto yy52;
				goto yy185;
			} else {
				if (yych <= 't') goto yy186;
				if (yych <= 'z') goto yy52;
			}
		}
	}
yy129:
#line 78 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kIN); }
#line 1205 "ext/rbs_extension/lexer.c"
yy130:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy187;
	goto yy53;
yy131:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy188;
	goto yy53;
yy132:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy190;
	goto yy53;
yy133:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy192;
	if (yych == 'i') goto yy193;
	goto yy53;
yy134:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'b') goto yy194;
	goto yy53;
yy135:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy195;
	goto yy53;
yy136:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy196;
	goto yy53;
yy137:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'i') goto yy197;
	goto yy53;
yy138:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'p') goto yy198;
	goto yy53;
yy139:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'u') goto yy200;
	goto yy53;
yy140:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'p') goto yy201;
	goto yy53;
yy141:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'c') goto yy202;
	if (yych == 't') goto yy203;
	goto yy53;
yy142:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy204;
	goto yy53;
yy143:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'i') goto yy206;
	goto yy53;
yy144:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy207;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy207;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy207;
		goto yy68;
	}
yy145:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '/') goto yy68;
	if (yych <= '9') goto yy66;
	if (yych <= '`') goto yy68;
	if (yych <= 'f') goto yy66;
	goto yy68;
yy146:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 0x00000000) goto yy68;
	if (yych == ')') goto yy208;
	goto yy146;
yy147:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 0x00000000) goto yy68;
	if (yych == '>') goto yy209;
	goto yy147;
yy148:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 0x00000000) goto yy68;
	if (yych == ']') goto yy210;
	goto yy148;
yy149:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 0x00000000) goto yy68;
	if (yych == '}') goto yy211;
	goto yy149;
yy150:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 0x00000000) goto yy68;
	if (yych == '|') goto yy212;
	goto yy150;
yy151:
	yyaccept = 5;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych <= '\'') {
		if (yych <= 0x00000000) goto yy78;
		if (yych <= '&') goto yy75;
		goto yy77;
	} else {
		if (yych == '\\') goto yy79;
		goto yy75;
	}
yy152:
	rbs_skip(state);
#line 38 "ext/rbs_extension/lexer.re"
	{ return next_token(state, pDOT3); }
#line 1346 "ext/rbs_extension/lexer.c"
yy153:
	rbs_skip(state);
#line 111 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tDQSYMBOL); }
#line 1351 "ext/rbs_extension/lexer.c"
yy154:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'u') goto yy213;
	if (yych == 'x') goto yy214;
	goto yy86;
yy155:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= ',') {
		if (yych <= '\f') {
			if (yych <= 0x00000000) goto yy156;
			if (yych <= 0x00000008) goto yy155;
			if (yych >= '\v') goto yy155;
		} else {
			if (yych <= 0x0000001F) {
				if (yych >= 0x0000000E) goto yy155;
			} else {
				if (yych == '#') goto yy155;
			}
		}
	} else {
		if (yych <= '>') {
			if (yych <= '-') goto yy155;
			if (yych <= '/') goto yy156;
			if (yych <= '9') goto yy155;
		} else {
			if (yych <= '^') {
				if (yych <= 'Z') goto yy155;
			} else {
				if (yych <= 'z') goto yy155;
				if (yych >= 0x0000007F) goto yy155;
			}
		}
	}
yy156:
#line 128 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tSYMBOL); }
#line 1390 "ext/rbs_extension/lexer.c"
yy157:
	rbs_skip(state);
	goto yy156;
yy158:
	rbs_skip(state);
yy159:
#line 112 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tSQSYMBOL); }
#line 1399 "ext/rbs_extension/lexer.c"
yy160:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '\'') {
		if (yych <= 0x00000000) goto yy68;
		if (yych <= '&') goto yy89;
		goto yy215;
	} else {
		if (yych == '\\') goto yy160;
		goto yy89;
	}
yy161:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '>') goto yy88;
	goto yy85;
yy162:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '=') goto yy88;
	goto yy85;
yy163:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '^') {
		if (yych <= '@') goto yy68;
		if (yych <= 'Z') goto yy216;
		goto yy68;
	} else {
		if (yych == '`') goto yy68;
		if (yych <= 'z') goto yy216;
		goto yy68;
	}
yy164:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '>') {
		if (yych <= '/') {
			if (yych == '!') goto yy218;
		} else {
			if (yych <= '9') goto yy164;
			if (yych == '=') goto yy218;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '?') goto yy218;
			if (yych <= '@') goto yy165;
			if (yych <= 'Z') goto yy164;
		} else {
			if (yych == '`') goto yy165;
			if (yych <= 'z') goto yy164;
		}
	}
yy165:
#line 126 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tSYMBOL); }
#line 1456 "ext/rbs_extension/lexer.c"
yy166:
	rbs_skip(state);
	goto yy98;
yy167:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 'Z') {
		if (yych <= '/') goto yy168;
		if (yych <= '9') goto yy167;
		if (yych >= 'A') goto yy167;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy167;
		} else {
			if (yych <= '`') goto yy168;
			if (yych <= 'z') goto yy167;
		}
	}
yy168:
#line 140 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tA2IDENT); }
#line 1478 "ext/rbs_extension/lexer.c"
yy169:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 's') goto yy219;
	goto yy105;
yy170:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy221;
	goto yy112;
yy171:
	rbs_skip(state);
#line 40 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tQIDENT); }
#line 1493 "ext/rbs_extension/lexer.c"
yy172:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'a') goto yy222;
	goto yy53;
yy173:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'r') goto yy223;
	goto yy53;
yy174:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy224;
	goto yy53;
yy175:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy176;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy176;
			if (yych <= 'z') goto yy52;
		}
	}
yy176:
#line 72 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kBOT); }
#line 1531 "ext/rbs_extension/lexer.c"
yy177:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 's') goto yy226;
	goto yy53;
yy178:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy179;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy179;
			if (yych <= 'z') goto yy52;
		}
	}
yy179:
#line 74 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kDEF); }
#line 1559 "ext/rbs_extension/lexer.c"
yy180:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy181;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy181;
			if (yych <= 'z') goto yy52;
		}
	}
yy181:
#line 75 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kEND); }
#line 1582 "ext/rbs_extension/lexer.c"
yy182:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy227;
	goto yy53;
yy183:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 's') goto yy228;
	goto yy53;
yy184:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy229;
	goto yy53;
yy185:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy230;
	goto yy53;
yy186:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy231;
	goto yy53;
yy187:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'u') goto yy232;
	goto yy53;
yy188:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy189;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy189;
			if (yych <= 'z') goto yy52;
		}
	}
yy189:
#line 83 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kNIL); }
#line 1635 "ext/rbs_extension/lexer.c"
yy190:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy191;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy191;
			if (yych <= 'z') goto yy52;
		}
	}
yy191:
#line 84 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kOUT); }
#line 1658 "ext/rbs_extension/lexer.c"
yy192:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'p') goto yy233;
	goto yy53;
yy193:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'v') goto yy234;
	goto yy53;
yy194:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy235;
	goto yy53;
yy195:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'f') goto yy236;
	goto yy53;
yy196:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'g') goto yy238;
	goto yy53;
yy197:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'p') goto yy239;
	goto yy53;
yy198:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy199;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy199;
			if (yych <= 'z') goto yy52;
		}
	}
yy199:
#line 90 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kTOP); }
#line 1711 "ext/rbs_extension/lexer.c"
yy200:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy241;
	goto yy53;
yy201:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy243;
	goto yy53;
yy202:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'h') goto yy245;
	goto yy53;
yy203:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'y') goto yy246;
	goto yy53;
yy204:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy205;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy205;
			if (yych <= 'z') goto yy52;
		}
	}
yy205:
#line 96 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kUSE); }
#line 1754 "ext/rbs_extension/lexer.c"
yy206:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy247;
	goto yy53;
yy207:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy249;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy249;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy249;
		goto yy68;
	}
yy208:
	rbs_skip(state);
#line 55 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tANNOTATION); }
#line 1777 "ext/rbs_extension/lexer.c"
yy209:
	rbs_skip(state);
#line 58 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tANNOTATION); }
#line 1782 "ext/rbs_extension/lexer.c"
yy210:
	rbs_skip(state);
#line 56 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tANNOTATION); }
#line 1787 "ext/rbs_extension/lexer.c"
yy211:
	rbs_skip(state);
#line 54 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tANNOTATION); }
#line 1792 "ext/rbs_extension/lexer.c"
yy212:
	rbs_skip(state);
#line 57 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tANNOTATION); }
#line 1797 "ext/rbs_extension/lexer.c"
yy213:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy250;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy250;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy250;
		goto yy68;
	}
yy214:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '/') goto yy68;
	if (yych <= '9') goto yy86;
	if (yych <= '`') goto yy68;
	if (yych <= 'f') goto yy86;
	goto yy68;
yy215:
	yyaccept = 6;
	rbs_skip(state);
	backup = *state;
	yych = peek(state);
	if (yych <= '\'') {
		if (yych <= 0x00000000) goto yy159;
		if (yych <= '&') goto yy89;
		goto yy158;
	} else {
		if (yych == '\\') goto yy160;
		goto yy89;
	}
yy216:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '>') {
		if (yych <= '/') {
			if (yych == '!') goto yy251;
		} else {
			if (yych <= '9') goto yy216;
			if (yych == '=') goto yy251;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '?') goto yy251;
			if (yych <= '@') goto yy217;
			if (yych <= 'Z') goto yy216;
		} else {
			if (yych == '`') goto yy217;
			if (yych <= 'z') goto yy216;
		}
	}
yy217:
#line 127 "ext/rbs_extension/lexer.re"
	{ return next_token(state, tSYMBOL); }
#line 1855 "ext/rbs_extension/lexer.c"
yy218:
	rbs_skip(state);
	goto yy165;
yy219:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 'Z') {
		if (yych <= '/') goto yy220;
		if (yych <= '9') goto yy104;
		if (yych >= 'A') goto yy104;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy104;
		} else {
			if (yych <= '`') goto yy220;
			if (yych <= 'z') goto yy104;
		}
	}
yy220:
#line 99 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kATRBS); }
#line 1877 "ext/rbs_extension/lexer.c"
yy221:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy252;
	goto yy112;
yy222:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 's') goto yy253;
	goto yy53;
yy223:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '_') goto yy255;
	goto yy53;
yy224:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy225;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy225;
			if (yych <= 'z') goto yy52;
		}
	}
yy225:
#line 71 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kBOOL); }
#line 1915 "ext/rbs_extension/lexer.c"
yy226:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 's') goto yy256;
	goto yy53;
yy227:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy258;
	goto yy53;
yy228:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy259;
	goto yy53;
yy229:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'u') goto yy261;
	goto yy53;
yy230:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'a') goto yy262;
	goto yy53;
yy231:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'r') goto yy263;
	goto yy53;
yy232:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy264;
	goto yy53;
yy233:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy265;
	goto yy53;
yy234:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'a') goto yy266;
	goto yy53;
yy235:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'i') goto yy267;
	goto yy53;
yy236:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy237;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy237;
			if (yych <= 'z') goto yy52;
		}
	}
yy237:
#line 88 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kSELF); }
#line 1988 "ext/rbs_extension/lexer.c"
yy238:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'l') goto yy268;
	goto yy53;
yy239:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy240;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy240;
			if (yych <= 'z') goto yy52;
		}
	}
yy240:
#line 100 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kSKIP); }
#line 2016 "ext/rbs_extension/lexer.c"
yy241:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy242;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy242;
			if (yych <= 'z') goto yy52;
		}
	}
yy242:
#line 91 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kTRUE); }
#line 2039 "ext/rbs_extension/lexer.c"
yy243:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy244;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy244;
			if (yych <= 'z') goto yy52;
		}
	}
yy244:
#line 92 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kTYPE); }
#line 2062 "ext/rbs_extension/lexer.c"
yy245:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy269;
	goto yy53;
yy246:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'p') goto yy270;
	goto yy53;
yy247:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy248;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy248;
			if (yych <= 'z') goto yy52;
		}
	}
yy248:
#line 95 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kVOID); }
#line 2095 "ext/rbs_extension/lexer.c"
yy249:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy271;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy271;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy271;
		goto yy68;
	}
yy250:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy272;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy272;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy272;
		goto yy68;
	}
yy251:
	rbs_skip(state);
	goto yy217;
yy252:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy273;
	goto yy112;
yy253:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy254;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy254;
			if (yych <= 'z') goto yy52;
		}
	}
yy254:
#line 67 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kALIAS); }
#line 2152 "ext/rbs_extension/lexer.c"
yy255:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= 'q') {
		if (yych == 'a') goto yy274;
		goto yy53;
	} else {
		if (yych <= 'r') goto yy275;
		if (yych == 'w') goto yy276;
		goto yy53;
	}
yy256:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy257;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy257;
			if (yych <= 'z') goto yy52;
		}
	}
yy257:
#line 73 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kCLASS); }
#line 2186 "ext/rbs_extension/lexer.c"
yy258:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy277;
	goto yy53;
yy259:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy260;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy260;
			if (yych <= 'z') goto yy52;
		}
	}
yy260:
#line 77 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kFALSE); }
#line 2214 "ext/rbs_extension/lexer.c"
yy261:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy279;
	goto yy53;
yy262:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy280;
	goto yy53;
yy263:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'f') goto yy281;
	goto yy53;
yy264:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy282;
	goto yy53;
yy265:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy284;
	goto yy53;
yy266:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy285;
	goto yy53;
yy267:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'c') goto yy286;
	goto yy53;
yy268:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy288;
	goto yy53;
yy269:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'c') goto yy289;
	goto yy53;
yy270:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy290;
	goto yy53;
yy271:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy66;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy66;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy66;
		goto yy68;
	}
yy272:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy291;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy291;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy291;
		goto yy68;
	}
yy273:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '_') goto yy292;
	goto yy112;
yy274:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'c') goto yy293;
	goto yy53;
yy275:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy294;
	goto yy53;
yy276:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'r') goto yy295;
	goto yy53;
yy277:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy278;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy278;
			if (yych <= 'z') goto yy52;
		}
	}
yy278:
#line 76 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kEXTEND); }
#line 2333 "ext/rbs_extension/lexer.c"
yy279:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy296;
	goto yy53;
yy280:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'c') goto yy298;
	goto yy53;
yy281:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'a') goto yy299;
	goto yy53;
yy282:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy283;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy283;
			if (yych <= 'z') goto yy52;
		}
	}
yy283:
#line 82 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kMODULE); }
#line 2371 "ext/rbs_extension/lexer.c"
yy284:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy300;
	goto yy53;
yy285:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy302;
	goto yy53;
yy286:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy287;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy287;
			if (yych <= 'z') goto yy52;
		}
	}
yy287:
#line 87 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kPUBLIC); }
#line 2404 "ext/rbs_extension/lexer.c"
yy288:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy304;
	goto yy53;
yy289:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'k') goto yy305;
	goto yy53;
yy290:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy306;
	goto yy53;
yy291:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '@') {
		if (yych <= '/') goto yy68;
		if (yych <= '9') goto yy86;
		goto yy68;
	} else {
		if (yych <= 'F') goto yy86;
		if (yych <= '`') goto yy68;
		if (yych <= 'f') goto yy86;
		goto yy68;
	}
yy292:
	rbs_skip(state);
	yych = peek(state);
	if (yych == '_') goto yy308;
	goto yy112;
yy293:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'c') goto yy310;
	goto yy53;
yy294:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'a') goto yy311;
	goto yy53;
yy295:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'i') goto yy312;
	goto yy53;
yy296:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy297;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy297;
			if (yych <= 'z') goto yy52;
		}
	}
yy297:
#line 79 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kINCLUDE); }
#line 2475 "ext/rbs_extension/lexer.c"
yy298:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy313;
	goto yy53;
yy299:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'c') goto yy315;
	goto yy53;
yy300:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy301;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy301;
			if (yych <= 'z') goto yy52;
		}
	}
yy301:
#line 85 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kPREPEND); }
#line 2508 "ext/rbs_extension/lexer.c"
yy302:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy303;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy303;
			if (yych <= 'z') goto yy52;
		}
	}
yy303:
#line 86 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kPRIVATE); }
#line 2531 "ext/rbs_extension/lexer.c"
yy304:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy316;
	goto yy53;
yy305:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy317;
	goto yy53;
yy306:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy307;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy307;
			if (yych <= 'z') goto yy52;
		}
	}
yy307:
#line 94 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kUNTYPED); }
#line 2564 "ext/rbs_extension/lexer.c"
yy308:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy111;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy309;
			if (yych <= 'Z') goto yy111;
		} else {
			if (yych == '`') goto yy309;
			if (yych <= 'z') goto yy111;
		}
	}
yy309:
#line 98 "ext/rbs_extension/lexer.re"
	{ return next_token(state, k__TODO__); }
#line 2587 "ext/rbs_extension/lexer.c"
yy310:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy318;
	goto yy53;
yy311:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy319;
	goto yy53;
yy312:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 't') goto yy320;
	goto yy53;
yy313:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy314;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy314;
			if (yych <= 'z') goto yy52;
		}
	}
yy314:
#line 80 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kINSTANCE); }
#line 2625 "ext/rbs_extension/lexer.c"
yy315:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy321;
	goto yy53;
yy316:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'n') goto yy323;
	goto yy53;
yy317:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'd') goto yy325;
	goto yy53;
yy318:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 's') goto yy327;
	goto yy53;
yy319:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy328;
	goto yy53;
yy320:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'e') goto yy329;
	goto yy53;
yy321:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy322;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy322;
			if (yych <= 'z') goto yy52;
		}
	}
yy322:
#line 81 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kINTERFACE); }
#line 2678 "ext/rbs_extension/lexer.c"
yy323:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy324;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy324;
			if (yych <= 'z') goto yy52;
		}
	}
yy324:
#line 89 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kSINGLETON); }
#line 2701 "ext/rbs_extension/lexer.c"
yy325:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy326;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy326;
			if (yych <= 'z') goto yy52;
		}
	}
yy326:
#line 93 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kUNCHECKED); }
#line 2724 "ext/rbs_extension/lexer.c"
yy327:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 's') goto yy330;
	goto yy53;
yy328:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'r') goto yy331;
	goto yy53;
yy329:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'r') goto yy333;
	goto yy53;
yy330:
	rbs_skip(state);
	yych = peek(state);
	if (yych == 'o') goto yy335;
	goto yy53;
yy331:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy332;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy332;
			if (yych <= 'z') goto yy52;
		}
	}
yy332:
#line 69 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kATTRREADER); }
#line 2767 "ext/rbs_extension/lexer.c"
yy333:
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy334;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy334;
			if (yych <= 'z') goto yy52;
		}
	}
yy334:
#line 70 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kATTRWRITER); }
#line 2790 "ext/rbs_extension/lexer.c"
yy335:
	rbs_skip(state);
	yych = peek(state);
	if (yych != 'r') goto yy53;
	rbs_skip(state);
	yych = peek(state);
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == '!') goto yy108;
		} else {
			if (yych <= '9') goto yy52;
			if (yych >= '=') goto yy109;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy336;
			if (yych <= 'Z') goto yy52;
		} else {
			if (yych == '`') goto yy336;
			if (yych <= 'z') goto yy52;
		}
	}
yy336:
#line 68 "ext/rbs_extension/lexer.re"
	{ return next_token(state, kATTRACCESSOR); }
#line 2816 "ext/rbs_extension/lexer.c"
}
#line 149 "ext/rbs_extension/lexer.re"

}
