module Bundler
  class LockfileParser
    def initialize: (String) -> void
    def specs: () -> Array[LazySpecification]
  end

  class LazySpecification
    def name: () -> String
    def version: () -> String
  end
end
