module RBS
  module Collection
    class Cleaner
      attr_reader lock: Config

      def initialize: (lock: Config) -> void

      def clean: () -> void

      def needed?: (String gem_name, String version) -> bool
    end
  end
end
