module RBS
  module Collection
    class Installer
      METADATA_FILENAME: String

      attr_reader lockfile: Config

      def initialize: (lockfile_path: Pathname) -> void
      def install_from_lockfile: () -> void

      private

      def collection_for: (Config::gem_entry) -> Collections::_Collection

      def format_config_entry: (Config::gem_entry) -> String
    end
  end
end
