name: RBS Comments

on:
  push:
    branches:
      - master
  pull_request: {}
  merge_group: {}

jobs:
  comments:
    runs-on: "ubuntu-latest"
    # env:
    #   RUBY_COMMIT: v4.0.0-preview2
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: "4.0.6"
          bundler: none
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdb-dev curl
      - name: Update rubygems & bundler
        run: |
          ruby -v
          gem update --system
      - name: install erb
        run: gem install erb
      - name: bin/setup
        run: |
          bin/setup
      - name: Check if `rake annotate` has been executed
        run: |
          git config --global --add safe.directory `pwd`
          bundle exec rake annotate confirm_annotation
