name: RBS Comments

on:
  push:
    branches:
      - master
  pull_request: {}
  merge_group: {}

jobs:
  comments:
    runs-on: "ubuntu-latest"
    # env:
    #   RUBY_COMMIT: v4.0.0-preview2
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: "4.0.1"
          bundler: none
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdb-dev curl
      - name: Update rubygems & bundler
        run: |
          ruby -v
          gem update --system
      - name: install erb
        run: gem install erb
      - name: bin/setup
        run: |
          bin/setup
      - name: Check if `rake annotate` has been executed
        run: |
          git config --global --add safe.directory `pwd`
          bundle exec rake annotate confirm_annotation
