name: Confirm PRs have milestones

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
    paths:
      - lib/**/*
      - core/**/*
      - stdlib/**/*
      - sig/**/*
      - rbs.gemspec

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - if: github.event.pull_request.milestone == null
        run: |
          echo "No milestone is given"
          exit 1
      - if: github.event.pull_request.milestone != null
        run: |
          echo "Milestone is given 💪"
